valgrind-gcc:
    image: ubuntu:xenial
    commands:
        - ./build/docker/script/run valgrind-gcc
valgrind-clang:
    image: ubuntu:xenial
    commands:
        - ./build/docker/script/run valgrind-clang
