language: cpp

script:
    - ./build/docker/docker -j3 $DOCKER $SPEC

matrix:
  include:
    - sudo: required
      env: DOCKER=ubuntu:yakkety SPEC=valgrind-gcc
      services:
        - docker

    - sudo: required
      env: DOCKER=ubuntu:yakkety SPEC=valgrind-clang
      services:
        - docker

    - sudo: required
      env: DOCKER=ubuntu:yakkety SPEC=coveralls
      services:
        - docker

    - sudo: required
      env: DOCKER=debian:testing SPEC=valgrind-gcc
      services:
        - docker

    - sudo: required
      env: DOCKER=debian:testing SPEC=valgrind-clang
      services:
        - docker
