language: cpp

script:
    - export make_flags="-j3"
    - export configure_flags="--disable-static $COVERAGE"
    - export make_check_name="check-am$VALGRIND"
    - ./build/docker/script/run travis-like

matrix:
  include:

    - sudo: false
      env: COVERAGE=--enable-coverage
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
          sources:
            - ubuntu-toolchain-r-test

    - sudo: false
      env: VALGRIND=-valgrind
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
