language: cpp

matrix:
  include:
    - env: BUILD_TYPE="vanilla"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Release"
           CXXFLAGS="-Werror"
      script:
        - ./.ci/docker/setup ubuntu:artful cmake
      services:
        - docker
      sudo: required

    - env: BUILD_TYPE="asan"
           CFLAGS="-fsanitize=address"
           CXXFLAGS="-fsanitize=address"
           LDFLAGS="-fsanitize=address"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Debug"
      script:
        - ./.ci/docker/setup ubuntu:artful cmake
      services:
        - docker
      sudo: required

    - env: BUILD_TYPE="tsan"
           CFLAGS="-fsanitize=thread -g -O2"
           CXXFLAGS="-fsanitize=thread -g -O2"
           LDFLAGS="-fsanitize=thread"
      script:
        - ./.ci/docker/setup ubuntu:artful cmake
      services:
        - docker
      sudo: required

    - env: BUILD_TYPE="lsan"
           CFLAGS="-fsanitize=leak"
           CXXFLAGS="-fsanitize=leak"
           LDFLAGS="-fsanitize=leak"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Debug"
      script:
        - ./.ci/docker/setup ubuntu:artful cmake
      services:
        - docker
      sudo: required

    - env: BUILD_TYPE="ubsan"
           CFLAGS="-fsanitize=undefined -fno-sanitize-recover"
           CXXFLAGS="-fsanitize=undefined -fno-sanitize-recover"
           LDFLAGS="-fsanitize=undefined"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Debug"
      script:
        - ./.ci/docker/setup ubuntu:artful cmake
      services:
        - docker
      sudo: required

    # Note: with CFLAGS="-Werror" ./configure fails for this job (see #1318)
    - sudo: required
      env: DOCKER_SPEC=coveralls pkg_make_flags="V=0 -j3"
           CXXFLAGS="-Werror"
      services:
        - docker
      script:
        - ./build/ci/travis
