language: cpp

script:
    - ./build/ci/travis

matrix:
  include:

    - sudo: required
      env: DOCKER_SPEC=valgrind-clang pkg_make_flags="V=0 -j3"
      services:
        - docker

    - sudo: required
      env: DOCKER_SPEC=valgrind-gcc pkg_make_flags="V=0 -j3"
      services:
        - docker

    - sudo: required
      env: DOCKER_SPEC=coveralls pkg_make_flags="V=0 -j3"
      services:
        - docker
