language: cpp

script:
    - ./build/travis "$BRANCHES_ONLY" -j3 $DOCKER $SPEC

matrix:
  include:
    - sudo: required
      env: DOCKER=ubuntu:yakkety SPEC=valgrind-gcc
           BRANCHES_ONLY=$TRAVIS_BRANCH
      services:
        - docker

    - sudo: required
      env: DOCKER=ubuntu:yakkety SPEC=coveralls
           BRANCHES_ONLY=$TRAVIS_BRANCH
      services:
        - docker

    - sudo: required
      env: DOCKER=ubuntu:yakkety SPEC=valgrind-clang
           BRANCHES_ONLY="master stable fix/ci"
      services:
        - docker
