language: cpp

matrix:
  include:
    - env: CXXFLAGS="-Werror"
      script:
        - ./.ci/docker/setup ubuntu:artful cmake
      services:
        - docker
      sudo: required

    - env: BUILD_TYPE="asan"
           CFLAGS="-fsanitize=address"
           CXXFLAGS="-fsanitize=address"
           LDFLAGS="-fsanitize=address"
           CMAKE_OPTIONS="-G Ninja -D CMAKE_BUILD_TYPE=Debug"
      script:
        - ./.ci/docker/setup ubuntu:artful cmake
      services:
        - docker
      sudo: required

    - sudo: required
      env: DOCKER_SPEC=valgrind-clang pkg_make_flags="V=0 -j3"
           CXXFLAGS="-Werror" CFLAGS="-Werror"
      services:
        - docker
      script:
        - ./build/ci/travis

    # Note: with CFLAGS="-Werror" ./configure fails for this job (see #1318)
    - sudo: required
      env: DOCKER_SPEC=valgrind-gcc pkg_make_flags="V=0 -j3"
           CXXFLAGS="-Werror"
      services:
        - docker
      script:
        - ./build/ci/travis

    # Note: with CFLAGS="-Werror" ./configure fails for this job (see #1318)
    - sudo: required
      env: DOCKER_SPEC=coveralls pkg_make_flags="V=0 -j3"
           CXXFLAGS="-Werror"
      services:
        - docker
      script:
        - ./build/ci/travis
