language: cpp

script:
    - ./build/travis

matrix:
  include:

    - sudo: false
      compiler: gcc-6
      env: COVERAGE=--enable-coverage CXX_NAME=g++-6 CC_NAME=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
          sources:
            - ubuntu-toolchain-r-test

    - sudo: false
      compiler: gcc-6
      env: CXX_NAME=g++-6 CC_NAME=gcc-6 VALGRIND=-valgrind
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
