language: cpp

install:
    - if [ "$COVERAGE" = "--enable-coverage" ]; then
        pip install --user cpp-coveralls;
      fi
    - ./autogen.sh

script:
    - export CXX="$CXX_NAME" CC="$CC_NAME";
    - export pkg_make_flags="V=0 -j3"
    - export pkg_configure_flags="--quiet --disable-static"
    # On 12.04 the linker needs LD_RUN_PATH otherwise the linking fails
    - export LD_RUN_PATH=$TRAVIS_BUILD_DIR/builtin
    # So, here we build our dependencies because it doesn't take too much time,
    # because travis uses 12.04 with very old libs which cause many warnings
    # with the also very old valgrind available:
    - ./build/dependency geoip
    - ./build/dependency libressl
    - ./build/dependency libevent
    - ./configure $pkg_configure_flags --with-geoip=builtin
        --with-openssl=builtin --with-libevent=builtin $COVERAGE
    - make $pkg_make_flags
    - make $pkg_make_flags check-am$VALGRIND
    - if [ -f test-suite.log ]; then cat test-suite.log; fi

# Silence gcov standard output since it produces way too much output
after_success:
    - if [ "$COVERAGE" = "--enable-coverage" ]; then
        coveralls --gcov /usr/bin/gcov-6 --exclude src/libmeasurement_kit/ext
                  -b .  --exclude example --exclude third_party
                  --exclude include/measurement_kit/ext
                  --exclude src/libmeasurement_kit/cmdline > /dev/null;
      fi

matrix:
  include:

    - sudo: false
      compiler: gcc-6
      env: COVERAGE=--enable-coverage CXX_NAME=g++-6 CC_NAME=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
          sources:
            - ubuntu-toolchain-r-test

    - sudo: false
      compiler: gcc-6
      env: CXX_NAME=g++-6 CC_NAME=gcc-6 VALGRIND=-valgrind
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
