language: cpp

script:
    - if [ "$DOCKER" != "" -a "$SPEC" != "" ]; then
        ./build/docker/docker -j3 $DOCKER $SPEC
      else
        export make_flags="-j3"
        export configure_flags="--disable-static $COVERAGE"
        export make_check_name="check-am$VALGRIND"
        ./build/docker/script/run travis-like build_dependency autogen
            configure make make_check finalize
      fi

matrix:
  include:

    - sudo: required
      env: DOCKER=ubuntu:yakkety SPEC=valgrind-gcc

    - sudo: required
      env: DOCKER=ubuntu:yakkety SPEC=valgrind-clang

    - sudo: required
      env: DOCKER=debian:testing SPEC=valgrind-gcc

    - sudo: required
      env: DOCKER=debian:testing SPEC=valgrind-clang

    - sudo: false
      env: COVERAGE=--enable-coverage
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
          sources:
            - ubuntu-toolchain-r-test

    - sudo: false
      env: VALGRIND=-valgrind
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
