language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --force-yes gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90
  - sudo apt-get install tor
  - pip install --user cpp-coveralls

install:
  - autoreconf -i
  - ./build/dependency all

# Only measure coverage with clang for now because I cannot manage to
# convince coveralls to find all sources when using gcc-4.8 and gcov-4.8
# (For more context see measurement-kit/measurement-kit#255)
script:
  - if [ "$CXX" = "clang++" ]; then
      ./configure -q --with-libevent=builtin --with-yaml-cpp=builtin
                     --with-boost=builtin --with-jansson=builtin
                     --with-libmaxminddb=builtin --with-Catch=builtin
                     --with-http-parser=builtin
                     CFLAGS=--coverage CXXFLAGS=--coverage
                     LDFLAGS=--coverage;
    else
      ./configure -q --with-libevent=builtin --with-yaml-cpp=builtin
                     --with-boost=builtin --with-jansson=builtin
                     --with-libmaxminddb=builtin --with-Catch=builtin
                     --with-http-parser=builtin;
    fi
  - make -j2 V=0
  - make -j2 check-am V=0

# Silence gcov standard output since it produces way too much output
after_success:
  - if [ "$CXX" = "clang++" ]; then
      coveralls --gcov /usr/bin/gcov-4.6 --exclude src/ext > /dev/null;
    fi

compiler:
  - clang
  - g++
