image: Visual Studio 2017

environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      BUILD_TOOL: msys2

    - BUILD_TOOL: msvc
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

build_script:
  - cmd: .ci\appveyor\%BUILD_TOOL%.bat
