name: build
on: [push, pull_request]
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build-type: ["asan", "clang", "coverage", "ubsan", "vanilla"]
    steps:
      - uses: actions/checkout@v2
      - name: run the build inside docker
        run: ./.ci/travis/script/travis "${{ matrix.build-type }}"
