name: vanilla
on: [push, pull_request]
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.14"]
    steps:
      - uses: actions/checkout@v2
      - name: run the build inside docker
        run: ./.ci/travis/script/travis vanilla
