name: vanilla
on: [push, pull_request]
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.14"]
    steps:
      - uses: actions/checkout@v2
      - name: install library dependencies
        run: sudo apt install libevent-dev libcurl4-openssl-dev libmaxminddb-dev libssl-dev
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure
      - name: make
        run: make V=0 -j`nproc`
      - name: make check
        run: make V=0 check -j`nproc`
